apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: TZ
          value: Europe/Paris
        volumeMounts:
        - mountPath: /data/db
          name: mono-data
      restartPolicy: Always
      volumes:
      - name: mono-data
        persistentVolumeClaim:
          claimName: mono-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
  clusterIP: None