apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: mongo-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-db
  name: mongo-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Paris
        image: mongo
        name: mongo_db
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-db-claim
      restartPolicy: Always
      volumes:
      - name: mongo-db-claim
        persistentVolumeClaim:
          claimName: mongo-db-claim
status: {}
