kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
