apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo-db-claim
  name: mongo-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
