apiVersion: v1
kind: Service
metadata:
  labels:
    app: myadmin
  name: myadmin
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 80
  selector:
    app: myadmin
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: myadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - image: nedeljkoradulovic88/phpmyadminbase:v1
        name: myadmin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
