apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: provider-claim
  name: provider-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
