apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark
  name: spark
spec:
  selector:
    matchLabels:
      app: spark
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: nedeljkoradulovic88/spark
        ports:
        - containerPort: 4040
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 7001
        - containerPort: 7002
        - containerPort: 7003
        - containerPort: 7004
        - containerPort: 7005
        - containerPort: 7006
        env:
        - name: PACKAGES
          value: org.apache.spark:spark-sql-kafka-0-10_2.11:2.3.1
        - name: SPARK_CONF_DIR
          value: /conf
        - name: TZ
          value: Europe/Paris
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
  name: spark
spec:
  ports:
  - name: "4040"
    port: 4040
    targetPort: 4040
  - name: "6066"
    port: 6066
    targetPort: 6066
  - name: "7077"
    port: 7077
    targetPort: 7077
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8081"
    port: 8081
    targetPort: 8081
  - name: "7001"
    port: 7001
    targetPort: 7001
  - name: "7002"
    port: 7002
    targetPort: 7002
  - name: "7003"
    port: 7003
    targetPort: 7003
  - name: "7004"
    port: 7004
    targetPort: 7004
  - name: "7005"
    port: 7005
    targetPort: 7005
  - name: "7006"
    port: 7006
    targetPort: 7006
  selector:
    app: spark
  clusterIP: None
