apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: sql-db-claim
  name: sql-db-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
