apiVersion: v1
kind: Service
metadata:
  name: sql-db
  labels:
    app: sql-db
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: sql-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
  labels:
    app: sql-db
spec:
  selector:
    matchLabels:
      app: sql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql-db
    spec:
      containers:
      - image: mysql:5.7.21
        name: sql-db
        env:
        - name: MYSQL_DATABASE
          value: sample
        - name: MYSQL_PASSWORD
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          value: supersecret
        - name: MYSQL_USER
          value: mysql
        - name: TZ
          value: Europe/Paris
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: sql-db-claim
          mountPath: /var/lib/mysql
      volumes:
      - name: sql-db-claim
        persistentVolumeClaim:
          claimName: sql-db-claim
status: {}
